# Generated by Django 3.0.1 on 2019-12-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191229_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo_post',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
